import { Manrope } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/layout/Navbar'
import Footer from '@/components/layout/Footer'
import Cart from './cart/Cart'
import { auth } from './auth'


const inter = Manrope({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({ children }) {

  const user = await auth()
  console.log(user)

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Cart user={user} />       
        <main className='relative '> 
          {children}
        </main>  
        <Footer />
      </body>
    </html>
  )
}
